// LendHub v2 - Ganache Deployment Addresses
// Auto-generated by deploy-ganache.js

const addresses = {
  // Mock Tokens
  WETH: "0x4a0788aFC182c2cC551E3F3D48CB0C33e96089e6",
  USDC: "0x280EA13C7595366327320C70647E287980f21AD9",
  DAI: "0x20Dcf1AE1d084AE846263940F6BE5952c7A2ab97",
  
  // Oracles
  WETH_USD_FEED: "0x7eED1a374827Baf64B1459d7AA400eE2b22fEaEd",
  USDC_USD_FEED: "0x4D5fcc195c34814D36b2e2F4965607B83FB2a970",
  DAI_USD_FEED: "0xB730455f41E0Eb066Dc0f799EB2D0785F041eE9e",
  
  // Core Contracts
  AddressToTokenMapV2: "0x70dE946bee6E23703266f8a6c023BEa7137414e2",
  LendingConfigV2: "0x03CC3Ac133fFD985Ba3F735384af25e388eA0d34",
  LendingHelper: "0x0a2758F02f7772CBEEBE93eb7c3e03f84180DA8A",
  
  // Pool Infrastructure
  PoolFactory: "0x958Be74b067E01A6c201c0A7B01506059aE6ccb3",
  IsolatedLendingPoolImpl: "0x5210392c0262bC84Db75f0d22F594A9d9D48964B",
  
  // Risk Management
  LiquidationManager: "0x0f1A7F8370E173F970e50a412bF4Ba3b71f326F5",
  KeeperAdapter: "0x9bC0ddbe3Eb6b051399F2c86B0f68E04AE1d424F",
  
  // Pools
  CORE_POOL: "0xeFE9fF217525Cc5ed370866281558CDd7e15aDa6",
};

// Legacy addresses for backward compatibility
const ETHAddress = "0x0000000000000000000000000000000000000000";
const LendingPoolAddress = addresses.CORE_POOL;
const LendingHelperAddress = addresses.LendingHelper;

module.exports = {
  default: addresses,
  addresses,
  ETHAddress,
  LendingPoolAddress,
  LendingHelperAddress
};