// LendHub v2 - Ganache Deployment Addresses
// Auto-generated by deploy-ganache.js

const addresses = {
  // Mock Tokens
  WETH: "0xF1149Fda5167481Be71d3875a736fC9eAf26EfeC",
  USDC: "0x10FF7891CDda38d946F802dA1897111a40f4832e",
  DAI: "0x12543c1F95BD5aC431dD80CCff9E1f658394447B",
  
  // Oracles
  WETH_USD_FEED: "0xdA115a74D279228E3B07f03B14F39e70043aD729",
  USDC_USD_FEED: "0x26265412a5eB4763cf97E5D655F25DCd8e4a736e",
  DAI_USD_FEED: "0xfbe9eeD68D72f5b2c368C00a6720b591506aF52b",
  
  // Core Contracts
  AddressToTokenMapV2: "0x749E3B64FcFE065d4966F146CFE51c986445c56B",
  LendingConfigV2: "0xf4C2e7D31706424145c10fb1e7892E135d246AAE",
  LendingHelper: "0x483604908fd5bf0F0c0f8043A2CA81819daF5f91",
  
  // Pool Infrastructure
  PoolFactory: "0x51EafFF82C9e0AE9a996449F708ed8aE789310b6",
  IsolatedLendingPoolImpl: "0xeC4309aefda07740e23EC480B5C92ca4A387338B",
  
  // Risk Management
  LiquidationManager: "0x8cd10C54712445B9389f9264Ca8823E2557765D6",
  KeeperAdapter: "0xfe6944D530E35cdD80a56729a3003Fa8d1311fB1",
  
  // Pools
  CORE_POOL: "0x996B93fc599F9e9f5E23b6BaB0DC7A9207950443",
};

// Legacy addresses for backward compatibility
const ETHAddress = "0x0000000000000000000000000000000000000000";
const LendingPoolAddress = addresses.CORE_POOL;
const LendingHelperAddress = addresses.LendingHelper;

module.exports = {
  default: addresses,
  addresses,
  ETHAddress,
  LendingPoolAddress,
  LendingHelperAddress
};