// LendHub v2 - Ganache Deployment Addresses
// Auto-generated by deploy-ganache.js

const addresses = {
  // Mock Tokens
  WETH: "0x5E55961B93EEecF9f1852A2d0208Be95b434ad8c",
  USDC: "0x865eD7303AB19fC1C1453a081aA12f754C111a56",
  DAI: "0xa78A548438DE3Ac86A14266A913A9aCa201f0210",
  
  // Oracles
  WETH_USD_FEED: "0xA04Eb8490d28B78B7f1c75eB86Be33F31F9a10E0",
  USDC_USD_FEED: "0x88764FdC87918E7eD7829d71e171B8664d3bb2A2",
  DAI_USD_FEED: "0xbA666EB2B7370E9AB1Cdfc709569f6452b04772E",
  
  // Core Contracts
  AddressToTokenMapV2: "0x4Ff13ac857F456A10F2EE859AE9A3C62e5e1C61A",
  LendingConfigV2: "0xb4b2925EefB2809ED7455A4CC4328ea60cA2A533",
  LendingHelper: "0x6b70f44539530f81BDe1b5489B70C5eD28E5a6ef",
  
  // Pool Infrastructure
  PoolFactory: "0x6C80234A091cF8a9fe9d1c22b6bf2Ddb9176E4D9",
  IsolatedLendingPoolImpl: "0x20860EC90C0C16f06f60a6D4a812751F333C022a",
  
  // Risk Management
  LiquidationManager: "0xB4c7D9d5b848573Dd3B44B741F4D28fa6aeDfb73",
  KeeperAdapter: "0xcf66297b78eb018ad4D01ef10f92F9C0b65783D8",
  
  // Pools
  CORE_POOL: "0x6739F8bf3b2315272BBC8B85Ef1EF9C0E300C3A7",
};

// Legacy addresses for backward compatibility
const ETHAddress = "0x0000000000000000000000000000000000000000";
const LendingPoolAddress = addresses.CORE_POOL;
const LendingHelperAddress = addresses.LendingHelper;

module.exports = {
  default: addresses,
  addresses,
  ETHAddress,
  LendingPoolAddress,
  LendingHelperAddress
};